#!/bin/bash
rm -rf lammps/*
mkdir lammps/monomer_0
cp back/* lammps/monomer_0
if ! command -v conda &> /dev/null; then
    echo "❌ Conda not found. Please install Anaconda or Miniconda."
    exit 1
fi
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate AmberTools23 || {
    echo "❌ AmberTools23 environment not found."
    exit 1
}
cp structures/monomer_0.smi test.smi
taskset --cpu-list 0 obabel -ismi test.smi -omol2 --gen3d --partialcharge eem -O monomer_com1.mol2
antechamber -i monomer_com1.mol2 -fi mol2 -fo mol2 -o monomer_com2.mol2 -pf y -at gaff
../Util/Util_monomer_modify_4_polymer_end_H_make/exe
cp monomer_reorder2.mol2 mol2tolt/test/monomer.mol2
cp polymer_new.lt moltemplates/polymer.lt
cp system_new.lt moltemplates/system.lt
cd mol2tolt/
./run.sh
cp test/monomer.lt ../moltemplates/monomer_add.lt
cd ..
cd moltemplates
../../Util/moltemplate-master/moltemplate/scripts/moltemplate.sh system.lt > moltemplate.log 2>&1
cp system.data ../lammps/monomer_0/system.data
cd ..
cd moltemplates
cp system.data ../ratio_calculation/polymer/system.data
cd ../ratio_calculation/polymer
../../../Util/lammps-2Aug2023/src/lmp_serial -i run_polymer_mass.npt2
python polymer_mass.py
cp extracted_mass.txt ../extracted_mass.txt
cd ../..
cp solvent/solvent.smi solvent.smi
taskset --cpu-list 0 obabel -ismi solvent.smi -omol2 --gen3d --partialcharge eem -O solvent_com1.mol2
antechamber -i solvent_com1.mol2 -fi mol2 -fo mol2 -o solvent_com2.mol2 -pf y -at gaff
cp solvent_com2.mol2 mol2tolt_solvent/test/solvent.mol2
cd mol2tolt_solvent/
./run.sh
cp test/solvent.lt ../moltemplates_solvent_single/solvent.lt
cd ..
cd moltemplates_solvent_single
../../Util/moltemplate-master/moltemplate/scripts/moltemplate.sh system.lt > moltemplate.log 2>&1
cp system.data ../ratio_calculation/solvent/system.data
cd ../ratio_calculation/solvent
../../../Util/lammps-2Aug2023/src/lmp_serial -in run_solvent_mass.npt2
python solvent_mass.py
cp extracted_solvent_mass.txt ../extracted_solvent_mass.txt
cd ..
python number_solvnet.py
python factoring.py
python solvent_lt.py
cp system_solvent.lt ../system_solvent.lt
cd ..
cp system_solvent.lt moltemplates_solvent/system.lt
cd mol2tolt_solvent/
./run.sh
cp test/solvent.lt ../moltemplates_solvent/solvent.lt
cd ..
cd moltemplates_solvent
../../Util/moltemplate-master/moltemplate/scripts/moltemplate.sh system.lt > moltemplate.log 2>&1
cp system.data ../lammps/monomer_0/system_solvent.data
cd ..
cd lammps/monomer_0
python ../../group_polymer.py
python ../../group_solvent.py
../../../Util/lammps-2Aug2023/src/lmp_serial -in run_iso.in.npt2_wo_strain
../../../Util/lammps-2Aug2023/src/lmp_serial -i run_iso.in.npt2_wo_strain_pppm
../../../Util/Util_Polymer_Solvent_Output/exe
